using System;

namespace App
{
	class Program
	{
		static void Main (string[] args)
		{
			// try... catch... finally
			int[] nums = new int[4]; // 3

			try
			{
				Console.WriteLine("Entered string:");
				string message = Console.ReadLine();

				if(message.Length>6)
				{
					throw new Exception("String length greater than 6 characters");
				}

				Console.WriteLine("End of try block");
			}
			catch(IndexOutOfRangeException ex)
			{
				Console.WriteLine($"Error occured: {ex.Message}");
			}
			catch(DivideByZeroException ex)
			{
				Console.WriteLine($"Error occured: {ex.Message}");
			}
			catch(Exception ex)
			{
				Console.WriteLine($"General error occured: {ex.Message}");
			}
			finally
			{
				Console.WriteLine("Finally block");
			}
			Console.ReadKey();
		}
	}
}
